In [1]:
# mathametical operations and functions on arrays 


import  numpy as np 

a=np.array([30,20,40,50,30,20])
b=np.array([10,20,40,20,10,40])
c=np.array([3])

print(a+b, np.add(a,b))
print(a-b, np.subtract(a,b))
print(a*b, np.multiply(a,b))
print(a/b, np.divide(a,b))
print(a**c, np.power(a,b))
print(a**(1/2), np.sqrt(a))



[40 40 80 70 40 60] [40 40 80 70 40 60]
[ 20   0   0  30  20 -20] [ 20   0   0  30  20 -20]
[ 300  400 1600 1000  300  800] [ 300  400 1600 1000  300  800]
[3.  1.  1.  2.5 3.  0.5] [3.  1.  1.  2.5 3.  0.5]
[ 27000   8000  64000 125000  27000   8000] [ 716276736          0          0 1443889152  716276736          0]
[5.47722558 4.47213595 6.32455532 7.07106781 5.47722558 4.47213595] [5.47722558 4.47213595 6.32455532 7.07106781 5.47722558 4.47213595]


In [2]:
# numpy----> creating array,slicing and Attributes

import numpy as np 
a=np.array([[1,2,3,4,5,6,7],[5,6,7,8,9,4,3]])
print(type(a))


# slicing
print(a[0:4,0:3])  # because show equal number of row and columns 
print(a[0,1:4])

#attribute of array
print(np.shape(a))      #given details about array m  x  n
print(np.size(a))       #number of element in array 
print(np.ndim(a))       #given dimension of array 
print(a.dtype)          #given data type of array
print(type(a))
print(len(a))           #give lenght of array
print(a.astype(float))  #type conversion 
print(a.astype(int))

<class 'numpy.ndarray'>
[[1 2 3]
 [5 6 7]]
[2 3 4]
(2, 7)
14
2
int32
<class 'numpy.ndarray'>
2
[[1. 2. 3. 4. 5. 6. 7.]
 [5. 6. 7. 8. 9. 4. 3.]]
[[1 2 3 4 5 6 7]
 [5 6 7 8 9 4 3]]


In [3]:
#CONCATENATE Array(numpy)

import numpy as np
a=np.array([1,2,3,4,5,6])
b=np.array([3,5,6,7,8,9])

print(np.concatenate([a,b]))

print(np.concatenate([a,b],axis=0))


[1 2 3 4 5 6 3 5 6 7 8 9]
[1 2 3 4 5 6 3 5 6 7 8 9]


In [4]:
import numpy as np

a=np.array([[1,2,3],[4,5,6]])
b=np.array([[3,5,6],[7,8,9]])

print(np.concatenate([a,b], axis=1))  # horizontal
print(np.hstack([a,b]))
print(np.concatenate([a,b],axis=0))   # vertical 
print(np.vstack([a,b]))


[[1 2 3 3 5 6]
 [4 5 6 7 8 9]]
[[1 2 3 3 5 6]
 [4 5 6 7 8 9]]
[[1 2 3]
 [4 5 6]
 [3 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [3 5 6]
 [7 8 9]]


In [5]:
#Adding and Removing Element in Array

import numpy as np
a=np.array([1,2,3,4,5,6])
print(np.append(a,90))

b=np.array([[1,2,3,4],[1,2,3,4]])
print(np.append(a,[99,77]))

print(np.insert(a,1,6))  # array , index , value 
print(np.insert(b,1,[1,2,39,4],axis=0))
print(b)

print(a)
print(np.delete(a,1))

print(b)
print(np.delete(b,1,axis=1))






[ 1  2  3  4  5  6 90]
[ 1  2  3  4  5  6 99 77]
[1 6 2 3 4 5 6]
[[ 1  2  3  4]
 [ 1  2 39  4]
 [ 1  2  3  4]]
[[1 2 3 4]
 [1 2 3 4]]
[1 2 3 4 5 6]
[1 3 4 5 6]
[[1 2 3 4]
 [1 2 3 4]]
[[1 3 4]
 [1 3 4]]


In [6]:
# Short ilter and search 

import numpy as np 

a=np.array([4,2,6,5,4,7,8,7,5,2,4,5,6,])
print(np.sort(a))
print(np.where(a==7))
#all evern number in array
print(np.where(a%2==0))
x=np.searchsorted(a,7)
print(x)


[2 2 4 4 4 5 5 5 6 6 7 7 8]
(array([5, 7], dtype=int64),)
(array([ 0,  1,  2,  4,  6,  9, 10, 12], dtype=int64),)
5


In [7]:
# AGGREGATING FUCTION IN ARRAY 
import numpy as np


In [8]:
# Questions numpy.1
 #Importing the NumPy library with an alias 'np'
import numpy as np

# Printing information about the np.add function using the np.info() method
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [9]:
# Questions mumpy.2

# Importing the NumPy library with an alias 'np'
import numpy as np

# Printing the version of NumPy installed
print(np.__version__)

# Printing the configuration details of NumPy
print(np.show_config())

1.26.4
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30153",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.8",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30153",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "openblas64",
      "found": true,
      "version": "0.3.23.dev",
      "detection method": "pkgconfig",
      "include directory": "/c/opt/64/include",
      "lib directory": "/c/opt/64/lib",
      "openblas configuration": "USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_

c:\Users\akash\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


In [10]:
# Questions numpy .3

# Importing the NumPy library with an alias 'np'
import numpy as np

# Creating a NumPy array 'x' containing elements 1, 2, 3, and 4
x = np.array([1, 2, 3, 4])

# Printing the original array 'x'
print("Original array:")
print(x)

# Checking if none of the elements in the array 'x' is zero and printing the result
print("Test if none of the elements of the said array is zero:")
print(np.all(x))

# Reassigning array 'x' to a new array containing elements 0, 1, 2, and 3
x = np.array([0, 1, 2, 3])

# Printing the new array 'x'
print("Original array:")
print(x)

# Checking if none of the elements in the updated array 'x' is zero and printing the result
print("Test if none of the elements of the said array is zero:")
print(np.all(x))

Original array:
[1 2 3 4]
Test if none of the elements of the said array is zero:
True
Original array:
[0 1 2 3]
Test if none of the elements of the said array is zero:
False


In [11]:
# Questions mumpy .4

# Write a NumPy program to test whether none of the elements of a given array are zero. 

# Importing the NumPy library with an alias 'np'
import numpy as np

# Creating a NumPy array 'x' containing elements 1, 2, 3, and 4
x = np.array([1, 2, 3, 4])

# Printing the original array 'x'
print("Original array:")
print(x)

# Checking if none of the elements in the array 'x' is zero and printing the result
print("Test if none of the elements of the said array is zero:")
print(np.all(x))

# Reassigning array 'x' to a new array containing elements 0, 1, 2, and 3
x = np.array([0, 1, 2, 3])

# Printing the new array 'x'
print("Original array:")
print(x)

# Checking if none of the elements in the updated array 'x' is zero and printing the result
print("Test if none of the elements of the said array is zero:")
print(np.all(x))

Original array:
[1 2 3 4]
Test if none of the elements of the said array is zero:
True
Original array:
[0 1 2 3]
Test if none of the elements of the said array is zero:
False


In [13]:
# Questions mumpy .5
# Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a number)

# Importing the NumPy library with an alias 'np'
import numpy as np

# Creating a NumPy array 'a' containing elements 1, 0, NaN (Not a Number), and infinity
a = np.array([1, 0, np.nan, np.inf])

# Printing the original array 'a'
print("Original array")
print(a)

# Checking the given array 'a' element-wise for finiteness and printing the result
print("Test a given array element-wise for finiteness :")
print(np.isfinite(a)) 

Original array
[ 1.  0. nan inf]
Test a given array element-wise for finiteness :
[ True  True False False]


In [15]:
# Questions mumpy .6
# Write a NumPy program to test elements-wise for positive or negative infinity .

# Importing the NumPy library with an alias 'np'
import numpy as np

# Creating a NumPy array 'a' containing elements 1, 0, NaN (Not a Number), and infinity
a = np.array([1, 0, np.nan, np.inf])

# Printing the original array 'a'
print("Original array")
print(a)

# Testing the given array 'a' element-wise for positive or negative infinity and printing the result
print("Test element-wise for positive or negative infinity:")
print(np.isinf(a)) 
     



Original array
[ 1.  0. nan inf]
Test element-wise for positive or negative infinity:
[False False False  True]


In [12]:
import numpy as np

a=np.array  ([[1,2],[3,4]])
b=np.array([[5,6], [7,8]])
print("Matrix A:\n", a)
print("\nMatrix B:\n", b    )

#Adding two matrices
c = a + b   
print("\n\nAddition of Matrix A and Matrix B:")    
print(c)      

#Subtracting matrix B from Matrix A
d = a - b    
print("\n\nSubtraction of Matrix B from Matrix A:")    
print(d)      

#Multiplying Matrices
e = np.dot(a , b)   #Standard dot product
f = np.matmul(a , b) #Matrix multiplication
g = a @ b          #Matrix multiplication using @ operator

print('\n\nDot Product       of Matrix A and Matrix B:')          
print('-------------------------')                                                      
print(e)                                                       

print('\n\nMatMul Function   of Matrix A and Matrix B:  ')                   
print('-------------------------')                                                                                     
print(f)                                                                        

print('\n\n@ Operator        of Matrix A and Matrix B:  ')                                          
print(g)                                                                                                                           

#Checking if the results are same or not
if e.all() == f.all()== g.all():
    print("\nAll methods give the same result.")    
else:
    print("\nSome methods don't give the same result.")          

#Finding transpose of Matrix

Matrix A:
 [[1 2]
 [3 4]]

Matrix B:
 [[5 6]
 [7 8]]


Addition of Matrix A and Matrix B:
[[ 6  8]
 [10 12]]


Subtraction of Matrix B from Matrix A:
[[-4 -4]
 [-4 -4]]


Dot Product       of Matrix A and Matrix B:
-------------------------
[[19 22]
 [43 50]]


MatMul Function   of Matrix A and Matrix B:  
-------------------------
[[19 22]
 [43 50]]


@ Operator        of Matrix A and Matrix B:  
[[19 22]
 [43 50]]

All methods give the same result.
